Add logs to client
kenshoo/jesque pull request #10
Opened 2017-11-02 16:34 UTC by dvizelman

Add logs to the client tracing job submission

2017-11-02 17:10 UTC, nanimrod approved these changes

2017-11-05 02:37 UTC, dvizelman commented
Client logs examples

Jesque event - JOB_PROCESS job=Job [class=CustomAction, args=[12, 2.3, false, reqs], vars=null] worker=resque:worker:dimav-e7470:3257-0:JAVA_DYNAMIC_QUEUES,highPriorityQueue,lowPriorityQueue


Jesque event - JOB_EXECUTE job=Job [class=CustomAction, args=[12, 2.3, false, reqs], vars=null] worker=resque:worker:dimav-e7470:3257-0:JAVA_DYNAMIC_QUEUES,highPriorityQueue,lowPriorityQueue


Jesque event - JOB_FAILURE job=Job [class=CustomAction, args=[12, 2.3, false, reqs], vars=null] worker=resque:worker:dimav-e7470:3793-0:JAVA_DYNAMIC_QUEUES highPriorityQueue,lowPriorityQueue
java.lang.RuntimeException: Inexpected failure
	at net.greghaines.jesque.worker.custom.actions.CustomAction.run(CustomAction.java:28)
	at net.greghaines.jesque.worker.WorkerImpl.execute(WorkerImpl.java:663)
	at net.greghaines.jesque.worker.WorkerImpl.process(WorkerImpl.java:614)
	at net.greghaines.jesque.worker.WorkerImpl.poll(WorkerImpl.java:459)
	at net.greghaines.jesque.worker.WorkerImpl.run(WorkerImpl.java:221)

2017-11-05 07:10 UTC, nanimrod requested changes

2017-11-05 07:10 UTC, nanimrod commented on src/main/java/net/greghaines/jesque/client/AbstractClient.java
> +        LOG.info("Starting " + enqueueType + " job" + jobJson + " to the queue " + queue + " with delay " + future);
This is harder to search in logz.io... please start with something more searchable.
Why aren't you using the parameters?

2017-11-05 07:10 UTC, nanimrod commented on src/main/java/net/greghaines/jesque/client/AbstractClient.java
> +            LOG.error(enqueueType + " job " + jobJson + " to the queue "+ queue + " has failed",e);
Same thing.

2017-11-05 07:10 UTC, nanimrod commented on src/main/java/net/greghaines/jesque/client/AbstractClient.java
> +            LOG.warn(duplicatedJobMessage);
Same

2017-11-05 07:10 UTC, nanimrod commented on src/main/java/net/greghaines/jesque/client/AbstractClient.java
> +        LOG.info(enqueueType + " job" + jobJson + " to the queue "+ queue + " has finished successfully");
same

2017-11-05 09:15 UTC, nanimrod approved these changes

2017-11-07 17:41 UTC, merged