lua based ack implementation
kenshoo/jesque pull request #3
Opened 2017-08-20 07:29 UTC by dvizelman

2017-08-20 08:53 UTC, nanimrod commented on src/main/java/net/greghaines/jesque/worker/Watchdog.java
> +        jedis.evalsha(this.RequeueJobsScriptHash.get(), 1, getServerName());
Please explain this line..

2017-08-20 09:50 UTC, nanimrod commented on src/main/java/net/greghaines/jesque/worker/Watchdog.java
> +                e.printStackTrace();
Please... never swallow an exception unless you have a very good reason to do so (almost never!).

2017-08-20 09:50 UTC, nanimrod commented on src/main/java/net/greghaines/jesque/worker/Watchdog.java
> +        jedis.evalsha(this.RequeueJobsScriptHash.get(), 1, getServerName());
Got it. Cool!!

2017-08-20 09:50 UTC, nanimrod commented on src/main/java/net/greghaines/jesque/worker/Watchdog.java
> +    private final AtomicReference<String> LightKeeperScriptHash = new AtomicReference<>(null);
Why do we need the AtomicReference?

2017-08-20 09:50 UTC, nanimrod commented on src/main/java/net/greghaines/jesque/worker/WorkerImpl.java
> +            this.jedis.evalsha(this.removeInFlightHash.get(), 2, key(INFLIGHT, this.name, curQueue),key("log"));
remove "this"

2017-08-20 09:50 UTC, nanimrod commented on src/main/resources/workerScripts/light_keeper.lua
> +local function inspectLiveKeeper(currentTime)
Why are you getting the currentTime from outside?

2017-08-20 09:50 UTC, nanimrod commented on src/main/java/net/greghaines/jesque/worker/WorkerImpl.java
> +                this.removeInFlightHash.set(this.jedis.scriptLoad(ScriptUtils.readScript(REMOVE_INFLIGHT_LUA)));;
Load the script only once.

2017-08-20 09:50 UTC, nanimrod commented on src/main/resources/workerScripts/light_keeper.lua
> +redis.call('SET', isAliveKey,currentTime)
What is that?

2017-08-20 09:50 UTC, nanimrod commented on src/main/resources/workerScripts/light_keeper.lua
> +inspectLiveKeeper(currentTime);
When are we scheduling this to run every 5 seconds?

2017-08-20 11:01 UTC, dvizelman commented on src/main/java/net/greghaines/jesque/worker/Watchdog.java
> +    private final AtomicReference<String> LightKeeperScriptHash = new AtomicReference<>(null);
While i can't see real need for AtomicReference in this case, I've followed the way scripts are loaded in WorkerImpl only as precaution and in order to save on consistency.

2017-08-20 11:03 UTC, dvizelman commented on src/main/java/net/greghaines/jesque/worker/Watchdog.java
> +                e.printStackTrace();
You are right, will fix it. I made quick fix in order to see error message and forgot to re-throw exception

2017-08-20 11:12 UTC, dvizelman commented on src/main/java/net/greghaines/jesque/worker/WorkerImpl.java
> +                this.removeInFlightHash.set(this.jedis.scriptLoad(ScriptUtils.readScript(REMOVE_INFLIGHT_LUA)));;
remove in flight cache is loaded only once ...

2017-08-20 11:29 UTC, dvizelman commented on src/main/java/net/greghaines/jesque/worker/WorkerImpl.java
> +            this.jedis.evalsha(this.removeInFlightHash.get(), 2, key(INFLIGHT, this.name, curQueue),key("log"));
Referencing instance variable thru **_this_** is the convention in this project, there are few other occurrences of **_this.jedis_** in this class. Why should we remove this exact reference that even was not introduced by us?

2017-08-20 11:33 UTC, dvizelman commented on src/main/resources/workerScripts/light_keeper.lua
> +local function inspectLiveKeeper(currentTime)
Ohh !!! I'll give another look on it. Generally, I was not able to use any global variable unless it was defined before function that is going to use it . And I didn't wanted to call redis.time again and again

2017-08-20 11:33 UTC, dvizelman commented on src/main/resources/workerScripts/light_keeper.lua
> +inspectLiveKeeper(currentTime);
Will be fixed

2017-08-20 11:35 UTC, dvizelman commented on src/main/resources/workerScripts/light_keeper.lua
> +redis.call('SET', isAliveKey,currentTime)
Updating is alive key every 2 sec on every server

2017-08-21 06:31 UTC, nanimrod commented on src/main/java/net/greghaines/jesque/worker/Watchdog.java
> +    private final AtomicReference<String> LightKeeperScriptHash = new AtomicReference<>(null);
Since it doesn't really have an affect, it's only confusing the reader.
I suggest to remove it.

2017-08-21 06:31 UTC, nanimrod commented on src/main/java/net/greghaines/jesque/worker/Watchdog.java
> +                e.printStackTrace();
So please commit a fix, so the PR will be cleaner :)

2017-08-21 06:31 UTC, nanimrod commented on src/main/java/net/greghaines/jesque/worker/WorkerImpl.java
> +            this.jedis.evalsha(this.removeInFlightHash.get(), 2, key(INFLIGHT, this.name, curQueue),key("log"));
OK, makes sense :)

2017-08-21 06:31 UTC, nanimrod commented on src/main/java/net/greghaines/jesque/worker/WorkerImpl.java
> +                this.removeInFlightHash.set(this.jedis.scriptLoad(ScriptUtils.readScript(REMOVE_INFLIGHT_LUA)));;
OK, I see.

2017-08-21 06:31 UTC, nanimrod commented on src/main/java/net/greghaines/jesque/worker/Watchdog.java
> +    public void activateLightKeeper() {
move to constructor...

2017-08-23 06:01 UTC, nanimrod requested changes

2017-08-23 06:01 UTC, nanimrod commented on src/main/java/net/greghaines/jesque/worker/Watchdog.java
> +
This method is doing too much and is a bit long... please break it down.

2017-08-23 10:58 UTC, dvizelman commented on src/main/java/net/greghaines/jesque/worker/Watchdog.java
> +
Done

2017-08-23 11:00 UTC, dvizelman commented
I feel like Watchdog needs to expose start method . just creating watchdog and expecting it to run automatically looks very unusual in code :
```

for (int i = 0; i < NUMBER_OF_WORKER_THREADS; i++) {
            final WorkerImpl worker = new WorkerImpl(
                    config,
                    Arrays.asList(HIGH.name(), LOW.name()),
                    redisJobService.getMapJobFactory(),
                    createJedis(config),
                    NextQueueStrategy.RESET_TO_HIGHEST_PRIORITY);
            final Thread workerThread = new Thread(worker);
            workerThread.start();
            workers.put(worker, workerThread);
        }

        new Watchdog(config, createJedis(config));
```

2017-08-23 12:15 UTC, dvizelman commented
I think the best would be to have start method just like Thread has.

2017-08-23 13:41 UTC, nanimrod commented
I don't like a solution that forces the client to run 2 methods when none of them has any meaning without the other.

2017-08-23 13:52 UTC, dvizelman commented
What 2 methods are you talking about? 1 method **_start_** , that's all . And that's the standard behaviour for Java as you can see from the Thread example.

2017-08-23 14:34 UTC, dvizelman commented
If I need to choose between 2 bad solutions: having everything executed in constructor or having static method executing watchdog initialization logic, I will go with the constructor. At least in my tests I could extend watchdog with class having empty constructor and set it instead the original one. Just in case, few links bellow are discussing what's wrong with static methods in java

https://testing.googleblog.com/2008/12/static-methods-are-death-to-testability.html
https://simpleprogrammer.com/2010/01/29/static-methods-will-shock-you/
https://mrtnrbrts.wordpress.com/2012/01/18/static-methods-in-java-are-evil-mostly/

2017-08-24 09:29 UTC, merged